#!/usr/bin/env bash

# ANSI color codes
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color (reset)

# Navigate to the project directory and set environment variables
cd /CarBnR_v3
export CARBNR_MYSQL_USER=carbnr_dev \
       CARBNR_MYSQL_PWD=carbnr_dev_pwd \
       CARBNR_MYSQL_HOST=localhost \
       CARBNR_MYSQL_DB=carbnr_dev_db \
       CARBNR_TYPE_STORAGE=db

# Store current directory
pwd_path=$(pwd)

# Start gunicorn processes in tmux sessions
tmux new-session -d 'gunicorn --bind 0.0.0.0:5002 api.v1.app:app'
tmux new-session -d 'gunicorn --bind 0.0.0.0:5000 carapp.select_cars:app'

# Wait for processes to start
sleep 2

# Check and report the status of the process on port 5000
pids_5000=$(lsof -t -i :5000 | tr '\n' ' ')  # Capture all PIDs in one line
if [[ -n "$pids_5000" ]]; then
  echo -e "\n${YELLOW}========== App on port 5000 ==========${NC}"
  echo -e "${GREEN}[*] App 'carapp.select_cars' started successfully in directory: $pwd_path${NC}"
  echo -e "${GREEN}[*] Process IDs: (${pids_5000})${NC}"
else
  echo -e "${RED}[-] Failed to start app 'carapp.select_cars' on port 5000.${NC}"
fi

# Check and report the status of the process on port 5002
pids_5002=$(lsof -t -i :5002 | tr '\n' ' ')  # Capture all PIDs in one line
if [[ -n "$pids_5002" ]]; then
  echo -e "\n${YELLOW}========== App on port 5002 ==========${NC}"
  echo -e "${GREEN}[*] App 'api.v1.app' started successfully in directory: $pwd_path${NC}"
  echo -e "${GREEN}[*] Process IDs: (${pids_5002})${NC}"
else
  echo -e "${RED}[-] Failed to start app 'api.v1.app' on port 5002.${NC}"
fi
